### ISSUE TITLE
Pak1 was needed to launch game 

### ISSUE THREAD

**Issue by RobinTPotter** [jonathanlinat/quake-leveldesign-starterkit#10]
Hi thanks for this is very useful to have in one place! 

Launcher would not launch map without pak1 also in place (instructions in linked article mentions this). It may not be necessary to run trenchbroom but seeing you are giving launch instructions its better to have pak1 because the error given by ironwail is only briefly visible in console before the quake menu appears.

**Comment by jonathanlinat** [comment]
Hello @RobinTPotter

Thanks for bringing this to my attention.

I wasn't sure it was necessary when I wrote the instructions. I'll update the README file in a couple of minutes to include your suggestion. 

Thank you again, and have a great day! 👋🏻
